### PR TITLE
Add project options: view logs & delete

### PR DESCRIPTION
**Pull request by jcapona**
| Status  | Ticket/Issue |
| :---: | :--: |
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1405) |

#### Main changes
Add more options to project menus. Now when accessing a project, a list will come up that will allow users to run projects, check the logs and delete the project folder.
- Added logic to log the output from a project run into a logfile inside the project folder. Had to set the `PYTHONUNBUFFERED` to `1` to be able to write to the logfile at runtime and not when the project-run finished. Note that the `pt-miniscreen` systemd service already sets that variable in its unit file.
- Added a `Scrollable` and `ScrollableTextFile` that take an image as an input and allow to scroll through it using the up/down buttons.

#### Screenshots (feature, test output, profiling, dev tools etc)

[insert screenshots here]

#### Other notes (e.g. implementation quirks, edge cases, questions / issues)
-

#### Manual testing tips
-

#### Tag anyone who definitely needs to review or help
-

### CODE REVIEW

**Comment by angusjfw** [comment]
When opening a large file (or perhaps corrupt - vim showed that it had a binary section) I got this error. We must ensure that button handling errors are caught before they break the app.

Also these battery charging state logs fire 3 times every 1 second regardless of what page you are on - that doesn't seem right.
```
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
ERROR:pt_miniscreen.app:Error in button handler:
Traceback (most recent call last):
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 103, in handler
    func()
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 57, in <lambda>
    lambda: self.root.handle_button(ButtonEvents.SELECT_RELEASE)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/root.py", line 183, in handle_button
    self.stack.push(component)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/core/components/stack.py", line 102, in push
    stack = self.state["stack"] + [self.create_child(Component)]
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/core/component.py", line 303, in create_child
    child = ChildComponent(**kwargs, on_rerender=self._reconcile)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/pages/root/projects.py", line 282, in __init__
    image = file_to_image(
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/utils.py", line 72, in file_to_image
    image = PIL.Image.new("1", text_size)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2634, in new
    return im._new(core.fill(mode, size, color))
MemoryError
DEBUG:pitop.common.lock:Lock file at /tmp/.com.pi-top.sdk.miniscreen.lock is not locked
ERROR:pt_miniscreen.app:Error in button handler: 'NoneType' object has no attribute 'is_screensaver_running'
Traceback (most recent call last):
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 97, in handler
    if self.root.is_screensaver_running:
AttributeError: 'NoneType' object has no attribute 'is_screensaver_running'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 97, in handler
    if self.root.is_screensaver_running:
AttributeError: 'NoneType' object has no attribute 'is_screensaver_running'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/pitop/common/ptdm.py", line 473, in __thread_method
    self.invoke_callback_func_if_exists(
  File "/usr/lib/python3/dist-packages/pitop/common/ptdm.py", line 489, in invoke_callback_func_if_exists
    func()
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/miniscreen.py", line 58, in <lambda>
    Message.PUB_V3_BUTTON_SELECT_RELEASED: lambda: set_button_state(
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/miniscreen.py", line 34, in set_button_state
    self.__ptdm_subscribe_client.invoke_callback_func_if_exists(
  File "/usr/lib/python3/dist-packages/pitop/common/ptdm.py", line 489, in invoke_callback_func_if_exists
    func()
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 108, in handler
    self.stop(e)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 145, in stop
    super().stop(error)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/core/app.py", line 37, in stop
    self.root._cleanup()
AttributeError: 'NoneType' object has no attribute '_cleanup'
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
Exception in thread Thread-269:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 161, in dim_and_start_screensaver_timer
    self.start_screensaver_timer()
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 154, in start_screensaver_timer
    self.SCREENSAVER_TIMEOUT, self.root.start_screensaver
AttributeError: 'NoneType' object has no attribute 'start_screensaver'
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
DEBUG:pitop.battery.battery:Charging state has not changed - doing nothing...
```

**Comment by angusjfw** [comment]
- opening fairly large files (~10k lines, 100kb) causes the app to hang for some time initially but does work great after that. if we have to load/render it all up front we should at least show a loading state
- Standard error logs are captured but stdout doesn't seem to be
- after reaching the bottom of a large log file i get stuck and can't scroll back up
- Logs pages should have the gutter icon for going back. a scroll postition indicator would also be really useful, though perhaps it's difficult to do that accurately given the issues with loading large files. line numbers could be very useful also.
- lone lines without spaces don't get split up and overflow the sides of the screen (eg the file path in python traceback log)
- - The text is centre aligned which doesn't really feel right for logs

**Comment by jcapona** [comment]
@angusjfw I think you didn't run the app with the latest changes from a few days ago, which addressed the loading and navigation issues; I tested using a log file that has ~100k lines (~500kb) and works okay since it loads the lines on request as you navigate; also, the issue where you can't go back up once you get to the bottom of the file is fixed, same as stderr logging.

I'll work on the last 3 points though!

**Comment by angusjfw** [comment]
- log line height is not enough when displaying a number on each line they are clipped
- sometimes when the lines have spaces to wrap properly a final character is hidden under the gutter area. perhaps the wrapping is expecting a full width screen but now the gutter is over some of that?
- the whole app still crashes if i open a non-utf file (eg bytes from /dev/random). we need to avoid errors in one part of the app escalating like this.

<details>
<summary>trace</summary>

```
ERROR:pt_miniscreen.app:Error in button handler: 'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte
Traceback (most recent call last):
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 103, in handler
    func()
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 57, in <lambda>
    lambda: self.root.handle_button(ButtonEvents.SELECT_RELEASE)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/root.py", line 188, in handle_button
    self.stack.push(component)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/core/components/stack.py", line 102, in push
    stack = self.state["stack"] + [self.create_child(Component)]
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/core/component.py", line 303, in create_child
    child = ChildComponent(**kwargs, on_rerender=self._reconcile)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/pages/root/projects.py", line 306, in __init__
    super().__init__(path=project_config.logfile, **kwargs)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/components/scrollable_text_file.py", line 45, in __init__
    self.file = TextFile(path)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/utils.py", line 51, in __init__
    for _ in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte
ERROR:pt_miniscreen.app:Error in button handler: 'NoneType' object has no attribute 'is_screensaver_running'
Traceback (most recent call last):
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 97, in handler
    if self.root.is_screensaver_running:
AttributeError: 'NoneType' object has no attribute 'is_screensaver_running'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 97, in handler
    if self.root.is_screensaver_running:
AttributeError: 'NoneType' object has no attribute 'is_screensaver_running'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/pitop/common/ptdm.py", line 473, in __thread_method
    self.invoke_callback_func_if_exists(
  File "/usr/lib/python3/dist-packages/pitop/common/ptdm.py", line 489, in invoke_callback_func_if_exists
    func()
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/miniscreen.py", line 48, in <lambda>
    Message.PUB_V3_BUTTON_DOWN_PRESSED: lambda: set_button_state(
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/miniscreen.py", line 34, in set_button_state
    self.__ptdm_subscribe_client.invoke_callback_func_if_exists(
  File "/usr/lib/python3/dist-packages/pitop/common/ptdm.py", line 489, in invoke_callback_func_if_exists
    func()
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 108, in handler
    self.stop(e)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/app.py", line 145, in stop
    super().stop(error)
  File "/home/pi/pi-top-4-Miniscreen/pt_miniscreen/core/app.py", line 37, in stop
    self.root._cleanup()
AttributeError: 'NoneType' object has no attribute '_cleanup'
```
</details>

**Review by angusjfw — APPROVED** [review]
Awesome!

**Pull request merged**
